/**
================================
Portfoilo of Shih-Kai of data.
================================
**/

// before title
var beforeIndex = [
{
	'index_id':'i00',
	'index_title':'ALL'
},
{
	'index_id':'i01',
	'index_title':'畢業製作'
},
{
	'index_id':'i02',
	'index_title':'其他作品'
}
];

// before data information
var beforeData = [
{
	'project_id':'p00',
	'cat_id':'i01',
	'project_title':'卡厝味',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p01',
	'cat_id':'i01',
	'project_title':'卡厝味_產品介紹',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p02',
	'cat_id':'i01',
	'project_title':'卡厝味_App介紹',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p03',
	'cat_id':'i02',
	'project_title':'3D建模',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p04',
	'cat_id':'i02',
	'project_title':'電子報',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p05',
	'cat_id':'i02',
	'project_title':'月曆設計',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p06',
	'cat_id':'i02',
	'project_title':'海報設計',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p07',
	'cat_id':'i02',
	'project_title':'MV動畫',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p08',
	'cat_id':'i02',
	'project_title':'插畫',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p09',
	'cat_id':'i02',
	'project_title':'手繪',
	'project_mainPic':'/images/i01@1x.jpg'
}
];
var beforeInformation = [
{
	'project_id':'p00',
	'project_title':'AAA',
	'project_Infor':'卡代表著我們的紙牌遊戲，厝是代表著家，家是一切最基本的社會，由家這個環境中，學習到人與人相處的方式，從這些相處之道凝煉出人生的智慧，卡牌中呈現出許多諺語的智慧，並帶著濃濃的台灣味。',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p00',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p00',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p01',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p01',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p02',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p03',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p04',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p04',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p05',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p05',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p06',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p07',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p07',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p08',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
},
{
	'project_id':'p09',
	'project_title':'AAA',
	'project_Infor':'',
	'project_Img':{
		'img01':'/images/02.jpg'
	}
}
];