/**
================================
Portfoilo of Shih-Kai of data.
================================
**/

// before title
var beforeIndex = [
{
	'index_id':'i00',
	'index_title':'ALL'
},
{
	'index_id':'i01',
	'index_title':'畢業製作'
},
{
	'index_id':'i02',
	'index_title':'其他作品'
}
];

// before data information
var beforeData = [
{
	'project_id':'p00',
	'cat_id':'i01',
	'project_title':'卡厝味',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p01',
	'cat_id':'i01',
	'project_title':'卡厝味_產品介紹',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p02',
	'cat_id':'i01',
	'project_title':'卡厝味_App介紹',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p03',
	'cat_id':'i02',
	'project_title':'3D建模',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p04',
	'cat_id':'i02',
	'project_title':'電子報',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p04',
	'cat_id':'i02',
	'project_title':'月曆設計',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p05',
	'cat_id':'i02',
	'project_title':'海報設計',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p06',
	'cat_id':'i02',
	'project_title':'MV動畫',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p07',
	'cat_id':'i02',
	'project_title':'插畫',
	'project_mainPic':'/images/i01@1x.jpg'
},
{
	'project_id':'p08',
	'cat_id':'i02',
	'project_title':'手繪',
	'project_mainPic':'/images/i01@1x.jpg'
}
];
var beforeInformation = [
{
	'project_id':'p01',
	'project_title':'AAA',
	'project_how':'',
	'project_what':'',
	'project_why':''
},
{
	'project_id':'p01',
	'project_title':'AAA',
	'project_how':'',
	'project_what':'',
	'project_why':''
},
{
	'project_id':'p01',
	'project_title':'AAA',
	'project_how':'',
	'project_what':'',
	'project_why':''
},
{
	'project_id':'p01',
	'project_title':'AAA',
	'project_how':'',
	'project_what':'',
	'project_why':''
},
{
	'project_id':'p01',
	'project_title':'AAA',
	'project_how':'',
	'project_what':'',
	'project_why':''
},
{
	'project_id':'p01',
	'project_title':'AAA',
	'project_how':'',
	'project_what':'',
	'project_why':''
},{},{},{},{},{},{},{},{}];